FROM ghcr.io/open-webui/open-webui:main

# Optional: Replace favicon icons
COPY ./contents/favicon.png /app/build/static/favicon.png

# Copy your custom CSS file
COPY ./contents/custom.css /app/build/static/custom.css

